export const formats = [
  { label: 'mp3', value: 'mp3' },
  { label: 'ogg', value: 'ogg_vorbis' },
  // { label: 'pcm', value: 'pcm' },
  // { label: 'json', value: 'json' }
];

export const genders = [
  { label: 'Male', value: 'male' },
  { label: 'Female', value: 'female' },
];

export const languages = [
  { label: 'English (US)', value: 'en-US' },
  { label: 'English (British) ', value: 'en-GB' },
  { label: 'English (Indian) ', value: 'en-IN' },
  { label: 'English (Australian)', value: 'en-AU' },
  { label: 'English (Welsh)', value: 'en-GB-WLS' },
  { label: 'Russian', value: 'ru-RU' },
  { label: 'Danish', value: 'da-DK' },
  { label: 'Dutch', value: 'nl-NL' },
  { label: 'Welsh', value: 'cy-GB' },
  { label: 'French', value: 'fr-FR' },
  { label: 'French (Canadian)', value: 'fr-CA' },
  { label: 'German', value: 'de-DE' },
  { label: 'Hindi', value: 'hi-IN' },
  { label: 'Icelandic', value: 'is-IS' },
  { label: 'Italian', value: 'it-IT' },
  { label: 'Japanese', value: 'ja-JP' },
  { label: 'Korean', value: 'ko-KR' },
  { label: 'Norwegian', value: 'nb-NO' },
  { label: 'Polish', value: 'pl-PL' },
  { label: 'Portuguese (Brazilian)', value: 'pt-BR' },
  { label: 'Portuguese (European)', value: 'pt-PT' },
  { label: 'Spanish (Castilian)', value: 'es-ES' },
  { label: 'Spanish (Latin American)', value: 'es-US' },
  { label: 'Romanian', value: 'ro-RO' },
  { label: 'Swedish', value: 'sv-SE' },
  { label: 'Turkish', value: 'tr-TR' },
];

export const voices = [
  { label: 'Mads, male', value: 'Mads', gender: 'male', language: 'da-DK' },
  { label: 'Naja, female', value: 'Naja', gender: 'female', language: 'da-DK' },
  { label: 'Lotte, female', value: 'Lotte', gender: 'female', language: 'nl-NL' },
  { label: 'Ruben, male', value: 'Ruben', gender: 'male', language: 'nl-NL' },
  { label: 'Nicole, female', value: 'Nicole', gender: 'female', language: 'en-AU' },
  { label: 'Russell, male', value: 'Russell', gender: 'male', language: 'en-AU' },
  { label: 'Amy, female', value: 'Amy', gender: 'female', language: 'en-GB' },
  { label: 'Brian, male', value: 'Brian', gender: 'male', language: 'en-GB' },
  { label: 'Emma, female', value: 'Emma', gender: 'female', language: 'en-GB' },
  { label: 'Aditi, female', value: 'Aditi', gender: 'female', language: 'en-IN' },
  { label: 'Aditi, female', value: 'Aditi', gender: 'female', language: 'hi-IN' },
  { label: 'Raveena, female', value: 'Raveena', gender: 'female', language: 'en-IN' },
  { label: 'Ivy, female', value: 'Ivy', gender: 'female', language: 'en-US' },
  { label: 'Joanna, female', value: 'Joanna', gender: 'female', language: 'en-US' },
  { label: 'Joey, male', value: 'Joey', gender: 'male', language: 'en-US' },
  { label: 'Justin, male', value: 'Justin', gender: 'male', language: 'en-US' },
  { label: 'Kendra, female', value: 'Kendra', gender: 'female', language: 'en-US' },
  { label: 'Kimberly, female', value: 'Kimberly', gender: 'female', language: 'en-US' },
  { label: 'Matthew, male', value: 'Matthew', gender: 'male', language: 'en-US' },
  { label: 'Salli, female', value: 'Salli', gender: 'female', language: 'en-US' },
  { label: 'Geraint, male', value: 'Geraint', gender: 'male', language: 'en-GB-WLS' },
  { label: 'Céline/Celine, female', value: 'Céline/Celine', gender: 'female', language: 'fr-FR' },
  { label: 'Mathieu, male', value: 'Mathieu', gender: 'male', language: 'fr-FR' },
  { label: 'Chantal, female', value: 'Chantal', gender: 'female', language: 'fr-CA' },
  { label: 'Hans, male', value: 'Hans', gender: 'male', language: 'de-DE' },
  { label: 'Marlene, female', value: 'Marlene', gender: 'female', language: 'de-DE' },
  { label: 'Vicki, female', value: 'Vicki', gender: 'female', language: 'de-DE' },
  { label: 'Dóra/Dora', value: 'Dóra/Dora', gender: 'female', language: 'is-IS' },
  { label: 'Karl, male', value: 'Karl', gender: 'male', language: 'is-IS' },
  { label: 'Carla, female', value: 'Carla', gender: 'female', language: 'it-IT' },
  { label: 'Giorgio, male', value: 'Giorgio', gender: 'male', language: 'it-IT' },
  { label: 'Mizuki, female', value: 'Mizuki', gender: 'female', language: 'jp-JP' },
  { label: 'Takumi, male', value: 'Takumi', gender: 'male', language: 'jp-JP' },
  { label: 'Seoyeon, female', value: 'Seoyeon', gender: 'female', language: 'ko-KR' },
  { label: 'Liv, female', value: 'Liv', gender: 'female', language: 'nb-NO' },
  { label: 'Jacek, male', value: 'Jacek', gender: 'male', language: 'pl-PL' },
  { label: 'Jan, male', value: 'Jan', gender: 'male', language: 'pl-PL' },
  { label: 'Ewa, female', value: 'Ewa', gender: 'female', language: 'pl-PL' },
  { label: 'Maja, female', value: 'Maja', gender: 'female', language: 'pl-PL' },
  { label: 'Ricardo, male', value: 'Ricardo', gender: 'male', language: 'pt-BR' },
  { label: 'Vitória/Vitoria, female', value: 'Vitória/Vitoria', gender: 'female', language: 'pt-BR' },
  { label: 'Cristiano, male', value: 'Cristiano', gender: 'male', language: 'pt-PT' },
  { label: 'Inês/Ines, female', value: 'Inês/Ines', gender: 'female', language: 'pt-PT' },
  { label: 'Carmen, female', value: 'Carmen', gender: 'female', language: 'ro-RO' },
  { label: 'Maxim, male', value: 'Maxim', gender: 'male', language: 'ru-RU' },
  { label: 'Tatyana, female', value: 'Tatyana', gender: 'female', language: 'ru-RU' },
  { label: 'Conchita, female', value: 'Conchita', gender: 'female', language: 'es-ES' },
  { label: 'Enrique, male', value: 'Enrique', gender: 'male', language: 'es-ES' },
  { label: 'Penélope/Penelope, female', value: 'Penélope/Penelope', gender: 'female', language: 'es-US' },
  { label: 'Miguel', value: 'Miguel', gender: 'male', language: 'es-US' },
  { label: 'Astrid', value: 'Astrid', gender: 'female', language: 'sv-SE' },
  { label: 'Filiz', value: 'Filiz', gender: 'female', language: 'tr-TR' },
  { label: 'Gwyneth', value: 'Gwyneth', gender: 'female', language: 'cy-GB' },
];

export const rates = [
  { label: '8000Hz', value: '8000' },
  { label: '16000Hz', value: '16000' },
  { label: '22050Hz', value: '22050' },
];
